### ISSUE TITLE
[MAPEAR PROCESSOS] - Mapear o Fluxo da VAN.

### ISSUE THREAD

**Issue by luizbraga22** [PadraoiX/Q-Ware-VAN-Projetos#1]
@tailayne-ferreira, a cada fluxo construído, marcar na caixinha abaixo e anexar no card específico o mapa e todo o processo de construção elaborado.

- [ ] - Mapear as aberturas de chamados - CARD #2 
- [ ] - Mapear os fluxos de arquivos  - CARD #3 
- [ ] - Mapear o banco de dados  - CARD #4 
- [ ] - Mapear os módulos do portal  - CARD #5
- [ ] - Mapear o fluxo da SAM - CARD #6
